FROM neo4j:latest
MAINTAINER Twein Yan <tweinyan@gmail.com>

COPY neo4j-spatial-0.25-neo4j-3.2.5-server-plugin.jar /var/lib/neo4j/plugins/neo4j-spatial-0.25-neo4j-3.2.5-server-plugin.jar
#RUN mkdir -p /var/lib/neo4j/plugins \
#        && cd /var/lib/neo4j/plugins \
#        && wget -O neo4j-spatial-0.25-neo4j-3.2.5-server-plugin.jar http://github.com/neo4j-contrib/m2/blob/master/releases/org/neo4j/neo4j-spatial/0.25-neo4j-3.2.5/neo4j-spatial-0.25-neo4j-3.2.5-server-plugin.jar?raw=true
